USE [master]
GO
CREATE LOGIN [Personajes] WITH PASSWORD=N'Personajes', DEFAULT_DATABASE=[DAI-DISNEY], CHECK_EXPIRATION=OFF,
CHECK_POLICY=OFF
GO

USE [DAI-Disney]
GO
CREATE USER [Personajes] FOR LOGIN [Personajes]
GO
USE [DAI-Disney]
GO
ALTER ROLE [db_owner] ADD MEMBER [Personajes]
GO